name = "eliuds-eggs"
version = "0.1.0"
defaultTargets = ["EliudsEggsTest"]
testDriver = "EliudsEggsTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "EliudsEggs"

[[lean_exe]]
name = "EliudsEggsTest"
root = "EliudsEggsTest"
