name = "rna-transcription"
version = "0.1.0"
defaultTargets = ["RnaTranscriptionTest"]
testDriver = "RnaTranscriptionTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "RnaTranscription"

[[lean_exe]]
name = "RnaTranscriptionTest"
root = "RnaTranscriptionTest"
